/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
  const ElCascader: typeof import('element-plus/es')['ElCascader']
  const ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
}
